#!/bin/bash -e
# shellcheck disable=SC2048
[ "$1" = "-h" ] || [ "$1" = "--help" ] && echo "Run an arbitrary command multiple times and count failures and fail ratio" && exit

fails=0
runs="${runs:-"20"}"
for ((i=1; i <= runs; i++)); do
    echo "## Run $i"
    $* || fails=$((fails+1))
    echo "## $(basename "$0"): Run: $i. Fails: $fails. Fail ratio $(bc <<< "${fails} * 100/${i}")%"
done
