#!/bin/sh -e
target="${target:-"$USER"}"
subject="${1:?"Need PR subject line"}"
shift
branch=$(git branch --show-current)
base=$(git branch -a | grep -o 'origin/\(master\|main\)' | tail -n1)

# Push the branch to the target fork
git push --force-with-lease "$target" "$branch"

# Create the PR with the custom title and commit list as the body
git log --pretty='* %s' "$base.." | gh pr create --head "$target:$branch" --title "$subject" --body-file - "$@"
