#!/bin/sh -e
target="${target:-"$USER"}"
subject="${1:?"Need PR subject line"}"
branch=$(git rev-parse --abbrev-ref HEAD)
git push $target --force-with-lease $branch && (echo -e "$subject\n\n" && \
base=$(git branch -a | grep 'origin/\(master\|main\)' | tail -n1)
git log --pretty='* %s' $base..) | hub pull-request -F -
