#!/bin/bash
## Usage: git-request-mail <user1> [<user2>]
## Send a pull request for the current branch to <user>@nx017 beginning at gerrit/master

GITROOT=$(git rev-parse --show-toplevel)

if [ $# -gt 2 ] && [ "$1" == "-s" ]; then
	shift
	subject=$1
	shift
elif [ $# -gt 1 ]; then
	subject="Review request"
else
	echo "Usage: git request-review [-s 'Topic'] <addr1> [<addr2> ...]"
	exit 1
fi

git request-pull gerrit/master $GITROOT | mutt -s "$subject" $@
