#!/bin/sh -e
target="${target:-"$USER"}"
branch=$(git branch --show-current)
title=$(git log -1 --format=%s)
body=$(git log -1 --format=%b)

git push "$target" "$branch" && gh pr create --head "$target:$branch" --title "$title" --body "$body" "$@"
