#!/bin/sh -e
shopt -s extglob
# by default select any spec file not created by services
spec="${spec:-"!(*:*).spec"}"
args="${args:-"--ccache --keep-pkgs=$HOME/local/tmp --prefer-pkgs=$HOME/local/tmp"}"
osc build $args $spec $@
