#!/bin/bash -e
build="${1:?"need build id"}"
arch="${arch:-"x86_64"}"
version="${version:-"12-SP3"}"
product="${product:-"Server"}"
curl -s ftp://openqa.suse.de/SLE-${version}-${product}-DVD-${arch}-Build${build}-Media1/ChangeLog | grep "${@:2}"
