#!/bin/bash -e
# two words with 5 characters each plus "-" plus two random digits = 13
# characters
words="${words:-2}"
word_length="${word_length:-5}"
digits="${digits:-2}"
xkcdpass -d '-' -n $words --max $word_length | sed "s/-/-${RANDOM:0:$digits}/"
