#!/bin/sh -e
zp_opts="${zp_opts:-""}"
# maybe is even safer: zypper ref && zypper -v dup --no-r -d  && zypper -v dup --no-r
# okurz: 2019-11-09: vendor changes should be controlled with proper
# repository priorities, not disallowed
#"$(dirname "$0")/zp" "${zp_opts}" dup --no-allow-vendor-change "$@"
"$(dirname "$0")/zp" "${zp_opts}" dup "$@"

# openqa packages will reset permissions. To use my custom group I need to set
# this properly every time an update of openQA or os-autoinst is done.
if [ -d /var/lib/openqa/factory ]; then
    sudo chown -R .openqa /var/lib/openqa/factory/ && sudo chmod -R g+rwX /var/lib/openqa/factory/
fi
