#!/bin/sh -e
package="${1:?"Need package name as first argument"}"
ssh o3 "sudo sed -n \"/|$package|/s/^.*|$package|[0-9]*\.[0-9]*\.[0-9]*\.\([a-f0-9]*\).*$/\1/p\" /var/log/zypp/history | tail -n 2 | sed -e :a -e 'N;s/\n/../;ba'"
